app_testimonials_api:
    resource: Manuxi\SuluTestimonialsBundle\Controller\Admin\TestimonialsController
    type: attribute
    options:
        expose: true

sulu_testimonials_settings_api:
    resource: Manuxi\SuluTestimonialsBundle\Controller\Admin\SettingsController
    type: attribute
    options:
        expose: true