app_testimonials_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluTestimonialsBundle\Controller\Admin\TestimonialsController
    name_prefix: sulu_testimonials.
    options:
        expose: true
sulu_testimonials_settings_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluTestimonialsBundle\Controller\Admin\SettingsController
    name_prefix: sulu_testimonials.
    options:
        expose: true